artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion
  source_URL: "https://drive.google.com/file/d/1f2YFj0UGUtmvLvo81d9nF6PSyd45WcpN/view?usp=drive_link"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
